[tool.poetry]
name = "dcache-pyclient"
version = "0.2.1"
description = "Python client for user interaction with dCache"
authors = ["Onno Zweers, Haili Hu"]
license = "GPL-3.0 license"
readme = "README.md"
packages = [
    { include = "ada", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.28.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.4.2"
flake8 = "^7.3.0"
pylint = "^3.3.9"
ruff = "^0.15.1"

[tool.poetry.group.test]
optional = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ada-cli = "ada.cli.app:main"
