# ADA configuration
#
# Command line and environmental variables will overwrite these.
# The order of precedence is for configuration is:
# 1. command line arguments
# 2. environment variables
# 3. ~/.ada/ada.conf
# 4. /etc/ada.conf
# 5. <script_dir>/etc/ada.conf

# API endpoint for dCache
api=api_url

# Authenticate with the token in this file.
# This can be an rclone config file with a bearer_token statement,
# or a plain file with only the token.
tokenfile=/path/to/token

# Use IGTF Grid certificates (default is true)
# Set to "true", if the dCache API uses an IGTF compatible certificate,
# also called a "Grid" certificate (tru for most dCache sites).
# Set to "false", if the dCache API has a "normal"
# certificate like a "Let's Encrypt" cert.
# igtf=true

# SSE channel timeout in seconds (default is 3600)
# channel_timeout=3600

# Set to "true" to show all API calls (default is false)
# debug=false

# curl netrc file containing username and password for authentication (default is ~/.netrc)
# netrcfile=~/.netrc
